test: test.o CString.o
	gcc test.o CString.o -o test -lm

test.o: test.c CString.h
	gcc -Wall -c test.c

CString.o: CString.c CString.h
	gcc -Wall -c CString.c  

clean:
	del test.o CString.o test.exe